[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=paref --no-cov-on-fail --cov-report=term-missing"
testpaths = [
    "tests",
]
